Homusubi_Anims = {  
    'idle': [], 
    'run': [], 
    'jump': [], 
    'fall': [], 
    'crouch': [], 
    'hit': [], 
    'LP': [], 
    'MP': [], 
    'HP': [],
    'LK': [], 
    'MK': [], 
    'HK': [],
    '2LP': [], 
    '2MP': [], 
    '2HP': [],
}
    # '2LK': [], 
    # '2MK': [], 
    # '2HK': [],
    # } 

Raijin_Anims = { 
    'idle': [], 
    'run': [], 
    'jump': [], 
    'fall': [], 
    'crouch': [], 
    'LP': [], 
    'MP': [], 
    'HP': [],
    'LK': [], 
    'MK': [], 
    'HK': [],
    }